import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from '@/styles/layouts/common.module.css';
import { Providers } from './providers';
import Header from './components/shared/header';
import Footer from './components/shared/footer';
import Sidebar from './components/shared/sidebar';
import Head from './head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head />
      <body className={inter.className}>
        <Providers>
          <div className={styles.wrapper}>
            <Header />
            <div className={styles.container}>
              <div className={styles.main}>
                {children}
              </div>
              <Sidebar />
            </div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
